/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import logica.AgenciaAlquilaVehiculos;
import logica.VCamion;
import logica.VTurismo;

/**
 *
 * @author David Padilla
 */
public class AgregaVehiculo extends javax.swing.JDialog {
    VCamion vc = null; //Variables que sirven como auxiliares
    VTurismo vt = null;

   //Constructor 
    public AgregaVehiculo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setResizable(false); //Anula maximizar
        this.setLocationRelativeTo(null); //Centra la ventana
        this.textNombre.requestFocus(); //Coloca el foco en el primer jText
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textMatricula = new javax.swing.JTextField();
        comboBoxTipoVehiculo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        botonAgregar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre: ");

        textNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreActionPerformed(evt);
            }
        });

        jLabel2.setText("Matrícula: ");

        textMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMatriculaActionPerformed(evt);
            }
        });

        comboBoxTipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Camion", "Turismo" }));
        comboBoxTipoVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTipoVehiculoActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo Vehículo: ");

        botonAgregar.setText("Agregar");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(textMatricula)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(49, 49, 49)
                                .addComponent(comboBoxTipoVehiculo, 0, 97, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(botonAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregar)
                    .addComponent(jButton2))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreActionPerformed
        this.textMatricula.requestFocus();
    }//GEN-LAST:event_textNombreActionPerformed

    private void textMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMatriculaActionPerformed
        this.comboBoxTipoVehiculo.requestFocus();
    }//GEN-LAST:event_textMatriculaActionPerformed

    private void comboBoxTipoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTipoVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxTipoVehiculoActionPerformed
//Botón que agrega un nuevo vehículo si ingresan los campos correctamente
    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        AgenciaAlquilaVehiculos aux = new AgenciaAlquilaVehiculos();
        if (comboBoxTipoVehiculo.getSelectedIndex() == 0){
            vc = new VCamion ();
            if (this.textNombre.getText().equals("")){
                JOptionPane.showMessageDialog( this, "Por Favor Digite Nombre", "Registro", JOptionPane.INFORMATION_MESSAGE);
                this.textNombre.requestFocus();
            }else{
                if (textMatricula.getText().length() != 6){
                    JOptionPane.showMessageDialog( this, "Caracteres de la matrícula incompletos", "Registro", JOptionPane.INFORMATION_MESSAGE);
                    this.textMatricula.requestFocus();
                }else{
                    if (isNumeric(textMatricula.getText().substring(3)) && isLetter(textMatricula.getText().substring(0,3))) {
                        vc.setNombre(textNombre.getText());
                        vc.setMatricula(textMatricula.getText().toUpperCase());
                        aux.guardaVehiculos (vc);
                        dispose();
                    }else{
                        JOptionPane.showMessageDialog( this, "Formato de la matrícula incorrecto (AAA000)", "Registro", JOptionPane.INFORMATION_MESSAGE);
                        this.textMatricula.requestFocus();
                    }
                }}
            }else{
                if (comboBoxTipoVehiculo.getSelectedIndex() == 1){
                    vt = new VTurismo ();
                    if (this.textNombre.getText().equals("")){
                        JOptionPane.showMessageDialog( this, "Por Favor Digite Nombre", "Registro", JOptionPane.INFORMATION_MESSAGE);
                        this.textNombre.requestFocus();
                    }else{
                        if (textMatricula.getText().length() != 6){
                            JOptionPane.showMessageDialog( this, "Caracteres de la matrícula incompletos", "Registro", JOptionPane.INFORMATION_MESSAGE);
                            this.textMatricula.requestFocus();
                        }else{
                            if (isNumeric(textMatricula.getText().substring(3)) && isLetter(textMatricula.getText().substring(0,3))) {
                                vt.setNombre(textNombre.getText());
                                vt.setMatricula(textMatricula.getText().toUpperCase());
                                aux.guardaVehiculos (vt);
                                dispose();
                            }else{
                                JOptionPane.showMessageDialog( this, "Formato de la matrícula incorrecto (AAA000)", "Registro", JOptionPane.INFORMATION_MESSAGE);
                                this.textMatricula.requestFocus();
                            }
                        }}
                    }
                }
    }//GEN-LAST:event_botonAgregarActionPerformed
//Botón que cierra la ventana sin agregar vehículo
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose ();
    }//GEN-LAST:event_jButton2ActionPerformed

    //Método tomado de: http://lineadecodigo.com/java/validar-si-un-dato-es-numerico-en-java/
    //Para saber si la cadena del parametro contiene solo numeros y retorna la respuesta true o false
    private static boolean isNumeric(String cadena){
        try {
            Integer.parseInt(cadena);
            return true;
        }catch (NumberFormatException nfe){
            return false;
        }
    }
 //Para saber si la cadena del parametro contiene solo letras y retorna la respuesta true o false   
    private static boolean isLetter (String cadena){
        cadena = cadena.toLowerCase();
   for(int i=0; i<cadena.length(); i++){
      if (!(cadena.charAt(i) >= 'a' && cadena.charAt(i) <= 'z') ){
         return false;
      }
   }
   return true;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JComboBox comboBoxTipoVehiculo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField textMatricula;
    private javax.swing.JTextField textNombre;
    // End of variables declaration//GEN-END:variables
}
