/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import logica.AgenciaAlquilaVehiculos;

/**
 *
 * @author David Padilla
 */
public class GaleriaImagenes extends javax.swing.JFrame {
//atributos necesrios para realizar algunas opciones
    File fichero;
    int ref;
    int cont;
    Icon icono = new ImageIcon(getClass().getResource("/iconos/no-foto.gif")); //carga una imagen que la usamos para cuando no exista una foto
    
    public GaleriaImagenes(int i) {
        initComponents();
        this.setResizable(false); //Anula maximizar
        this.setLocationRelativeTo(null); //Centra la ventana
        ref = i;
        cont = 0; // para recorrer el ArrayList de imagenes
        ImprimeFoto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMain = new javax.swing.JLabel();
        lblIzquierda = new javax.swing.JLabel();
        lblDerecha = new javax.swing.JLabel();
        botonAtras = new javax.swing.JButton();
        botonSiguiente = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        botonAgregaFoto = new javax.swing.JButton();
        botonEliminarFoto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblMain.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        botonAtras.setText("Atrás");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        botonSiguiente.setText("Siguiente");
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });

        jButton5.setText("Salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        botonAgregaFoto.setText("Agregar Foto");
        botonAgregaFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregaFotoActionPerformed(evt);
            }
        });

        botonEliminarFoto.setText("Eliminar Foto");
        botonEliminarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarFotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblIzquierda, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblMain, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDerecha, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(botonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSiguiente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonEliminarFoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonAgregaFoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMain, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAtras)
                    .addComponent(botonSiguiente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(botonAgregaFoto)
                    .addComponent(botonEliminarFoto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Boton salir
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dispose ();
    }//GEN-LAST:event_jButton5ActionPerformed
//Boton siguiente
    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguienteActionPerformed
        cont++;
        ImprimeFoto();
    }//GEN-LAST:event_botonSiguienteActionPerformed
//Boton Atrás
    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        cont--;
        ImprimeFoto();
    }//GEN-LAST:event_botonAtrasActionPerformed
//Agrega una nueva foto
    private void botonAgregaFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregaFotoActionPerformed
     //Código copiado y modificado para las necesidades,  disponible en: http://uh-tis.blogspot.com.co/2014/03/Curso-de-JAVA-Como-cargar-una-imagen-y-o-foto-en-un-JLabel-de-un-formulario-utilizando-JFileChooser.html  
        int resultado;
        CargaFoto ventana = new CargaFoto(this, true); 
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG y PNG","jpg","png");
        ventana.carga.setFileFilter(filtro);
        resultado= ventana.carga.showOpenDialog(null);
        if (JFileChooser.APPROVE_OPTION == resultado){
            fichero = ventana.carga.getSelectedFile();
            try{
                ImageIcon iconox = new ImageIcon(fichero.toString());
                AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos().get(ref).agregaFotoVehiculo(iconox, ref);
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, "Error abriendo la imagen "+ ex);  
            }
        }
        ImprimeFoto ();
    }//GEN-LAST:event_botonAgregaFotoActionPerformed
//elimina la foto que actualemnet este en el label main
    private void botonEliminarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarFotoActionPerformed
        ArrayList<ImageIcon> alii = AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos().get(ref).getFotos();
        if (!alii.isEmpty()){
            try{
        alii.remove(cont);
        AgenciaAlquilaVehiculos.nuevo.getListaVehiculos().get(ref).setFotos(alii);
        JOptionPane.showMessageDialog(null, "Foto eliminada exitosamente!");
        cont--;
        ImprimeFoto ();
            }catch (Exception exc){
                System.out.println(exc);
            }
        }
    }//GEN-LAST:event_botonEliminarFotoActionPerformed
//visualiza en los labels las fotos del ArrayList correspondiente
    private void ImprimeFoto (){
        ArrayList<ImageIcon> alii = AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos().get(ref).getFotos();
        Icon ico;
        if (!alii.isEmpty()){
        ico = new ImageIcon(alii.get(cont).getImage().getScaledInstance(lblMain.getWidth(), lblMain.getHeight(), Image.SCALE_DEFAULT));
        lblMain.setIcon(ico);
        }else{
            lblMain.setText("AGREGUE IMAGENES A LA GALERÍA");
        }
        
        if ((cont-1) < 0) { lblIzquierda.setIcon(icono); botonAtras.setEnabled(false); }
        else { 
            ico = new ImageIcon(alii.get(cont-1).getImage().getScaledInstance(lblIzquierda.getWidth(), lblIzquierda.getHeight(), Image.SCALE_DEFAULT));
            lblIzquierda.setIcon(ico); botonAtras.setEnabled(true); }
        
        if (alii.size() <= (cont+1)) { lblDerecha.setIcon(icono); botonSiguiente.setEnabled(false); }
        else { 
            ico = new ImageIcon(alii.get(cont+1).getImage().getScaledInstance(lblDerecha.getWidth(), lblDerecha.getHeight(), Image.SCALE_DEFAULT));
            lblDerecha.setIcon(ico); botonSiguiente.setEnabled(true); }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregaFoto;
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonEliminarFoto;
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel lblDerecha;
    private javax.swing.JLabel lblIzquierda;
    private javax.swing.JLabel lblMain;
    // End of variables declaration//GEN-END:variables
}
