
package vista;
import java.awt.Desktop;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import persistencia.Archivo;
import logica.AgenciaAlquilaVehiculos;
import logica.VCamion;
import logica.VTurismo;
import logica.Vehiculo;



/**
 *
 * @author David Padilla
 */
public class VentanaPrincipal extends javax.swing.JFrame {
     DefaultTableModel tabla1; //variables necesarias para las tablas
     DefaultTableModel tabla2;

 //Constructor   
    public VentanaPrincipal() {
        try {
            AgenciaAlquilaVehiculos.nuevo = (AgenciaAlquilaVehiculos) Archivo.loading("ArchivoAgencia.dat"); //carga el archivo
        }
        catch (IOException e) {}
        catch (ClassNotFoundException e) {}
        initComponents();
        this.setResizable(false); //Deshabilita la opción de maximizar la ventana.
        this.setLocationRelativeTo(null); //Centra la ventana
        agregaTablas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAgregaVehiculo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        textMatricula = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        muestraNombre = new javax.swing.JLabel();
        muestraMatricula = new javax.swing.JLabel();
        muestraTipo = new javax.swing.JLabel();
        muestraEstado = new javax.swing.JLabel();
        botonAgregaRenta = new javax.swing.JButton();
        botonDevolverVehiculo = new javax.swing.JButton();
        labelImage = new javax.swing.JLabel();
        botonVerGaleria = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDisponibles = new javax.swing.JTable();
        botonActualizar1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaAlquilados = new javax.swing.JTable();
        botonActualizar2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        botonSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agencia de Alquiler de Vehículos - "+AgenciaAlquilaVehiculos.getVehiculo().getNombre());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        botonAgregaVehiculo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonAgregaVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add-car.jpg"))); // NOI18N
        botonAgregaVehiculo.setText("Agregar Vehículo");
        botonAgregaVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregaVehiculoActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/images.jpg"))); // NOI18N

        textMatricula.setText("Ingrese matrícula");
        textMatricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textMatriculaMouseClicked(evt);
            }
        });
        textMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textMatriculaKeyPressed(evt);
            }
        });

        botonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/search-car.jpg"))); // NOI18N
        botonBuscar.setText("Buscar");
        botonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonBuscarMouseClicked(evt);
            }
        });
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botonAgregaRenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonAgregaRenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add-rent1.jpg"))); // NOI18N
        botonAgregaRenta.setText("Rentar");
        botonAgregaRenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregaRentaActionPerformed(evt);
            }
        });

        botonDevolverVehiculo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonDevolverVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/back-car.jpg"))); // NOI18N
        botonDevolverVehiculo.setText("Devolver");
        botonDevolverVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDevolverVehiculoActionPerformed(evt);
            }
        });

        botonVerGaleria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonVerGaleria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icono-camara.png"))); // NOI18N
        botonVerGaleria.setText("Ver Galería");
        botonVerGaleria.setPreferredSize(new java.awt.Dimension(115, 33));
        botonVerGaleria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerGaleriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(muestraNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(muestraMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(muestraTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(muestraEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                    .addComponent(botonVerGaleria, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(botonDevolverVehiculo)
                        .addGap(18, 18, 18)
                        .addComponent(botonAgregaRenta)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(textMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonBuscar)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(muestraNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(muestraMatricula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(muestraTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(muestraEstado))
                    .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregaRenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonDevolverVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVerGaleria, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ver Vehículos", jPanel1);

        tablaDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaDisponibles);

        botonActualizar1.setText("Actualizar");
        botonActualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonActualizar1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(botonActualizar1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Vehículos disponibles", jPanel2);

        tablaAlquilados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tablaAlquilados);

        botonActualizar2.setText("Actualizar");
        botonActualizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonActualizar2)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonActualizar2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vehículos Alquilados", jPanel3);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setText("Vehículos Turismo: "+AgenciaAlquilaVehiculos.getVehiculo().totalVehiculosTurismo()+"   Vehículos Camion: "+AgenciaAlquilaVehiculos.getVehiculo().totalVehiculosCamion()+"   Total Vehículos: "+AgenciaAlquilaVehiculos.getVehiculo().totalVehiculos());

        botonSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add-salir.png"))); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Agregar Vehículo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edición");

        jMenuItem3.setText("Modificar nombre Agencia");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Eliminar Vehículo");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem11.setText("Nuevo precio por kilometro");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuItem12.setText("Nuevo precio por día");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");

        jMenuItem5.setText("Acerca de...");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("Manual uso del software");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenu4.setText("Documentación");

        jMenuItem8.setText("Documento");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuItem9.setText("Videotutoriales");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuItem10.setText("Diagrama de clase");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenu3.add(jMenu4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addComponent(botonAgregaVehiculo)
                .addGap(18, 18, 18)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonSalir)
                            .addComponent(botonAgregaVehiculo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)))
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//visualiza el JDialog de AgregarVehiculo ademas de actualizar las tablas y la informacion de vehiculos
    private void botonAgregaVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregaVehiculoActionPerformed
        AgregaVehiculo avv = new AgregaVehiculo(this, true);
        avv.setVisible(true);
        agregaTablas ();
        jLabel2.setText(infoAgencia ());
    }//GEN-LAST:event_botonAgregaVehiculoActionPerformed
//limpia el jtext al hacer clic
    private void textMatriculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textMatriculaMouseClicked
        textMatricula.setText("");
    }//GEN-LAST:event_textMatriculaMouseClicked

    private void textMatriculaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textMatriculaKeyPressed

    }//GEN-LAST:event_textMatriculaKeyPressed

    private void botonBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBuscarMouseClicked
         
    }//GEN-LAST:event_botonBuscarMouseClicked
//Busca en el ArrayList la existencia de la matríacula y si existe imprime en pantalla los detalles del vehiculo
    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        if (AgenciaAlquilaVehiculos.getVehiculo().buscarVehiculo(textMatricula.getText(), AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos()) == -1){
            JOptionPane.showMessageDialog(null, "METRÍCULA INGRESADA INEXISTENTE", "ERROR DE ENTRADA", JOptionPane.WARNING_MESSAGE);
        }else{
            muestraNombre.setText("Nombre: "+AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos().get(AgenciaAlquilaVehiculos.getVehiculo().buscarVehiculo(textMatricula.getText(), AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos())).getNombre()) ;
            muestraMatricula.setText("Matrícula: "+AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos().get(AgenciaAlquilaVehiculos.getVehiculo().buscarVehiculo(textMatricula.getText(), AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos())).getMatricula()) ;
            muestraTipo.setText(AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos().get(AgenciaAlquilaVehiculos.getVehiculo().buscarVehiculo(textMatricula.getText(), AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos())).toString()) ;
            if (AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos().get(AgenciaAlquilaVehiculos.getVehiculo().buscarVehiculo(textMatricula.getText(), AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos())).isAlquilado() == true)
                muestraEstado.setText("Estado: Alquilado");
            else muestraEstado.setText("Estado: Disponible");
            if (AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos().get(AgenciaAlquilaVehiculos.getVehiculo().buscarVehiculo(textMatricula.getText(), AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos())).getFotos().size() != 0){
            Icon icono = new ImageIcon(AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos().get(AgenciaAlquilaVehiculos.getVehiculo().buscarVehiculo(textMatricula.getText(), AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos())).getFotos().get(0).getImage().getScaledInstance(labelImage.getWidth(), labelImage.getHeight(), Image.SCALE_DEFAULT));
            labelImage.setIcon( icono );
            }else{
                Icon icono = new ImageIcon(getClass().getResource("/iconos/no-foto.gif"));
                labelImage.setIcon(icono);
            }
        } 
    }//GEN-LAST:event_botonBuscarActionPerformed
//renta un vehiculo si este existe o si esta disponible
    private void botonAgregaRentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregaRentaActionPerformed
        if (AgenciaAlquilaVehiculos.getVehiculo().buscarVehiculo(textMatricula.getText(), AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos()) == -1){
            JOptionPane.showMessageDialog(null, "METRÍCULA INGRESADA INEXISTENTE", "ERROR DE ENTRADA", JOptionPane.WARNING_MESSAGE);
        }else{
        if (AgenciaAlquilaVehiculos.getVehiculo().alquilarVehiculo(AgenciaAlquilaVehiculos.getVehiculo().buscarVehiculo(textMatricula.getText(), AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos())) == true){
            JOptionPane.showMessageDialog(null, "Confirmacion Vehículo alquilado exitosamente!"); 
            agregaTablas ();
        }else {
            JOptionPane.showMessageDialog(null, "EL VEHÍCULO NO SE PUDO RENTAR", "ACCIÓN INVALIDADA", JOptionPane.WARNING_MESSAGE); 
        }
        }
    }//GEN-LAST:event_botonAgregaRentaActionPerformed
//Devuelve un vehículo si este se encuentra alquilado, ademas muestra un JOptionPane con la informacion de la factura
    private void botonDevolverVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDevolverVehiculoActionPerformed
        if (AgenciaAlquilaVehiculos.getVehiculo().buscarVehiculo(textMatricula.getText(), AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos()) == -1){
            JOptionPane.showMessageDialog(null, "METRÍCULA INGRESADA INEXISTENTE", "ERROR DE ENTRADA", JOptionPane.WARNING_MESSAGE);
        }else{
        if (AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos().get(AgenciaAlquilaVehiculos.getVehiculo().buscarVehiculo(textMatricula.getText(), AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos())).isAlquilado() == true){
            if (AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos().get(AgenciaAlquilaVehiculos.getVehiculo().buscarVehiculo(textMatricula.getText(), AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos())) instanceof VTurismo){
                VTurismo vt = new VTurismo ();
                vt = (VTurismo)AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos().get(AgenciaAlquilaVehiculos.getVehiculo().buscarVehiculo(textMatricula.getText(), AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos()));
                try{
                long nuevoKilometraje = Long.parseLong(JOptionPane.showInputDialog(null, "Ingrese nuevo registro del kilometraje"));
                if (nuevoKilometraje > vt.getKilometraje()){
                JOptionPane.showMessageDialog(null, "Total a Pagar: "+AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos().get(AgenciaAlquilaVehiculos.getVehiculo().buscarVehiculo(textMatricula.getText(), AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos())).devolverElVehiculo(AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos(), AgenciaAlquilaVehiculos.getVehiculo().buscarVehiculo(textMatricula.getText(), AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos()), nuevoKilometraje));
                vt.setKilometraje(nuevoKilometraje);
                vt.setAlquilado(false);
                AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos().set(AgenciaAlquilaVehiculos.getVehiculo().buscarVehiculo(textMatricula.getText(), AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos()), vt);
                }else{
                    JOptionPane.showMessageDialog(null, "Cifra ingresada incorrecta debe ser mayor a "+vt.getKilometraje() );
                }
                }catch (Exception asd){
                    JOptionPane.showMessageDialog(null, "Cifra ingresada incorrecta" );
                }
                
            }else{
                JOptionPane.showMessageDialog(null, "Total a Pagar: "+AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos().get(AgenciaAlquilaVehiculos.getVehiculo().buscarVehiculo(textMatricula.getText(), AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos())).devolverElVehiculo(AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos(), AgenciaAlquilaVehiculos.getVehiculo().buscarVehiculo(textMatricula.getText(), AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos()), 0));
            }
            agregaTablas ();
        }else{
            JOptionPane.showMessageDialog(null, "EL VEHÍCULO NO SE PUDO DEVOLVER", "ACCIÓN INVALIDADA", JOptionPane.WARNING_MESSAGE);
        }
        }
    }//GEN-LAST:event_botonDevolverVehiculoActionPerformed
//Guarda en el archivo y se sale del programa
    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        if( JOptionPane.showConfirmDialog( this, "seguro que quiere salir?", "Confirmacion", JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION){
        try {
            Archivo.saving(AgenciaAlquilaVehiculos.nuevo,"ArchivoAgencia.dat");
            this.dispose();
        }
        catch (ClassNotFoundException e){}
        catch (IOException e) {}
        catch(NullPointerException e){}
    }
    }//GEN-LAST:event_botonSalirActionPerformed
//Actualiza las tablas de vehiculos disponibles y alquilados, tambien la informacion de los vehiculos mostrada en la parte inferior del software
    private void botonActualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizar1ActionPerformed
        agregaTablas ();
        jLabel2.setText(infoAgencia ());
    }//GEN-LAST:event_botonActualizar1ActionPerformed
//Actualiza las tablas de vehiculos disponibles y alquilados, tambien la informacion de los vehiculos mostrada en la parte inferior del software
    private void botonActualizar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizar2ActionPerformed
        agregaTablas ();
        jLabel2.setText(infoAgencia ());
    }//GEN-LAST:event_botonActualizar2ActionPerformed
//Acción del item Agregar Vehículo, del menú Archivo, visualiza el JDialog AgregaVehiculo
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        AgregaVehiculo avv = new AgregaVehiculo(this, true);
        avv.setVisible(true);
        agregaTablas ();
        jLabel2.setText(infoAgencia ());
    }//GEN-LAST:event_jMenuItem1ActionPerformed
//Acción del item Salir, del menú Archivo, guarda en el archivo y cierra el programa
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if( JOptionPane.showConfirmDialog( this, "seguro que quiere salir?", "Confirmacion", JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION){
        try {
            Archivo.saving(AgenciaAlquilaVehiculos.nuevo,"ArchivoAgencia.dat");
            this.dispose();
        }
        catch (ClassNotFoundException e){}
        catch (IOException e) {}
        catch(NullPointerException e){}
    }
    }//GEN-LAST:event_jMenuItem2ActionPerformed
//Acción del item Modificar Nombre Agencia, del menú Edicón, modifica el nombre de la agencia
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        AgenciaAlquilaVehiculos.nuevo.setNombre(JOptionPane.showInputDialog(null, "Ingrese nuevo nombre a la Agencia"));
    }//GEN-LAST:event_jMenuItem3ActionPerformed
//Acción del item Eliminar Vehículo, del menú Edición, elimina un vehículo del ArrayList de la agencia
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        String placa;
        placa = JOptionPane.showInputDialog(null, "Ingrese Matrícula de Vehículo a eliminar");
         if (AgenciaAlquilaVehiculos.getVehiculo().buscarVehiculo(placa, AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos()) == -1){
            JOptionPane.showMessageDialog(null, "METRÍCULA INGRESADA INEXISTENTE", "ERROR DE ENTRADA", JOptionPane.WARNING_MESSAGE);
        }else{
             ArrayList<Vehiculo> aux = AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos();
             aux.remove(AgenciaAlquilaVehiculos.getVehiculo().buscarVehiculo(placa, AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos()));
             AgenciaAlquilaVehiculos.nuevo.setListaVehiculos(aux);
             JOptionPane.showMessageDialog(null, "VEHÍCULO ELIMINADO!", "INFORMACIÓN", JOptionPane.WARNING_MESSAGE);
             agregaTablas ();
             jLabel2.setText(infoAgencia ());
         }
    }//GEN-LAST:event_jMenuItem4ActionPerformed
//Acción del item Acerca De, del menú Ayuda, visualiza el JDialog con la informacion personal del proyecto
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        AcercaDe ad = new AcercaDe (this, false);
        ad.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
     //Código tomado de: https://franciscoguemes.wordpress.com/2011/08/03/abrir-documentos-pdf-word-etc-desde-java/
        try {
      File path = new File ("[Final]Documentación Proyecto final.pdf");
      Desktop.getDesktop().open(path);
      }catch (IOException ex) {
      ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
     //Código tomado de: https://franciscoguemes.wordpress.com/2011/08/03/abrir-documentos-pdf-word-etc-desde-java/   
        try {
      File path = new File ("Diagramadeclase.png");
      Desktop.getDesktop().open(path);
      }catch (IOException ex) {
      ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
     //código tomado de: https://franciscoguemes.wordpress.com/2011/08/03/abrir-documentos-pdf-word-etc-desde-java/   
        if(java.awt.Desktop.isDesktopSupported()){
           try{
             Desktop dk = Desktop.getDesktop();
             dk.browse(new URI("https://www.youtube.com/playlist?list=PLtfXtHoqP5U5P9ZrLeanKtf4ejWWSir4q"));
            }catch(Exception e){
             System.out.println("Error al abrir URL: "+e.getMessage());
             }
}
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        //código tomado de: https://franciscoguemes.wordpress.com/2011/08/03/abrir-documentos-pdf-word-etc-desde-java/   
        if(java.awt.Desktop.isDesktopSupported()){
           try{
             Desktop dk = Desktop.getDesktop();
             dk.browse(new URI("https://www.youtube.com/watch?v=EAbvMHr5P7w&feature=youtu.be"));
            }catch(Exception e){
             System.out.println("Error al abrir URL: "+e.getMessage());
             }
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed
//Para que al salir desde la "X" del programa o salida por defecto guarde en el arhivo
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if( JOptionPane.showConfirmDialog( this, "seguro que quiere salir?", "Confirmacion", JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION){
        try {
            Archivo.saving(AgenciaAlquilaVehiculos.nuevo,"ArchivoAgencia.dat");
            this.dispose();
        }
        catch (ClassNotFoundException e){}
        catch (IOException e) {}
        catch(NullPointerException e){}
        }
    }//GEN-LAST:event_formWindowClosing
//visualiza en pantalla la ventana de la galería donde podremos manejar y ver las fotos del vehículo
    private void botonVerGaleriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerGaleriaActionPerformed
        if (AgenciaAlquilaVehiculos.getVehiculo().buscarVehiculo(textMatricula.getText(), AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos()) == -1){
            JOptionPane.showMessageDialog(null, "METRÍCULA INGRESADA INEXISTENTE", "ERROR DE ENTRADA", JOptionPane.WARNING_MESSAGE);
        }else{
                GaleriaImagenes gi = new GaleriaImagenes(AgenciaAlquilaVehiculos.getVehiculo().buscarVehiculo(textMatricula.getText(), AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos()));
                gi.setVisible(true);
        }

    }//GEN-LAST:event_botonVerGaleriaActionPerformed
//Opcion del menú edicion, que modifica el precio por kilometro de alquiler de los vehiculos de tipo turismo
    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        try{
        AgenciaAlquilaVehiculos.getVehiculo().setP_p_kilometro(Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese nuevo precio por kilometro para vehículos de turismo")));
        }catch (Exception ex){
           JOptionPane.showMessageDialog(null, "CIFRA INVÁLIDA", "ERROR DE ENTRADA", JOptionPane.WARNING_MESSAGE); 
        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed
//Opcion del menú edicion, que modifica el precio por día de alquiler de los vehiculos de tipo camion
    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        try{
        AgenciaAlquilaVehiculos.getVehiculo().setP_p_dia(Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese nuevo precio por día para vehículos camión")));
        }catch (Exception ex){
           JOptionPane.showMessageDialog(null, "CIFRA INVÁLIDA", "ERROR DE ENTRADA", JOptionPane.WARNING_MESSAGE); 
        }
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) { //Método main
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }
    //Método que carga y actualiza las tablas de vehículos disponibles y alquilados
    public void agregaTablas (){
        tabla1 = new DefaultTableModel();
        tabla2 = new DefaultTableModel();
        tabla1.addColumn("Nombre"); tabla2.addColumn("Nombre");
        tabla1.addColumn("Matrícula"); tabla2.addColumn("Matrícula");
        tabla1.addColumn("Tipo"); tabla2.addColumn("Tipo");
        this.tablaDisponibles.setModel(tabla1);
        this.tablaAlquilados.setModel(tabla2);
        for (int i=0; i<AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos().size(); i++){
                String[] Datos = new String [3];
                Datos[0] = AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos().get(i).getNombre();
                Datos[1] = AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos().get(i).getMatricula();
                if (AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos().get(i) instanceof VTurismo) 
                    Datos[2] = "Vehículo Turismo";
                else Datos[2] = "Vehículo Camion";
            if (AgenciaAlquilaVehiculos.getVehiculo().getListaVehiculos().get(i).isAlquilado() == false){
                tabla1.addRow(Datos);
            }else {
                tabla2.addRow(Datos);
            }
        }  
    }
    //Método que actualiza la informacion mostrada en la parte inferior del software
    public String infoAgencia (){ 
        return "Vehículos Turismo: "+AgenciaAlquilaVehiculos.getVehiculo().totalVehiculosTurismo()+"   Vehículos Camion: "+AgenciaAlquilaVehiculos.getVehiculo().totalVehiculosCamion()+"   Total Vehículos: "+AgenciaAlquilaVehiculos.getVehiculo().totalVehiculos();
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar1;
    private javax.swing.JButton botonActualizar2;
    private javax.swing.JButton botonAgregaRenta;
    private javax.swing.JButton botonAgregaVehiculo;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonDevolverVehiculo;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonVerGaleria;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel muestraEstado;
    private javax.swing.JLabel muestraMatricula;
    private javax.swing.JLabel muestraNombre;
    private javax.swing.JLabel muestraTipo;
    private javax.swing.JTable tablaAlquilados;
    private javax.swing.JTable tablaDisponibles;
    private javax.swing.JTextField textMatricula;
    // End of variables declaration//GEN-END:variables
}
